-- Supabase schema for the Micro-SaaS Signal Engine.
--
-- This is the one table the app actually uses: "Push to Supabase" / background
-- sync (see addToSupabaseAction / syncToSupabaseAction in app/actions.ts) writes
-- saved ideas here using the public anon key.
--
-- Run this once in the Supabase SQL editor for your project.

CREATE TABLE IF NOT EXISTS saved_ideas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  tagline TEXT,
  problem TEXT,
  solution TEXT,
  target_audience TEXT,
  pain_solved TEXT,
  build_complexity TEXT,
  mrr_target TEXT,
  build_cost TEXT,
  launch_kit JSONB,
  user_email TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Row Level Security. The app inserts with the public anon key, so anon INSERT
-- is allowed — but do NOT grant anon SELECT, or every visitor could read all
-- users' saved ideas and email addresses. Read the table from the Supabase
-- dashboard or with the service-role key instead.
ALTER TABLE saved_ideas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon insert" ON saved_ideas;
CREATE POLICY "Allow anon insert" ON saved_ideas
  FOR INSERT TO anon
  WITH CHECK (true);

-- If you see "schema cache" errors after creating the table, reload the cache:
--   NOTIFY pgrst, 'reload schema';


-- ---------------------------------------------------------------------------
-- secret_keys — server-side credential mirror written by POST /api/secrets/seed
-- and audited by the scheduled agent at GET /api/cron/agent.
--
-- Values are stored as the "enc:v1:<iv>:<tag>:<ciphertext>" AES-256-GCM
-- envelope produced by encryptSecret() in app/security.ts, keyed on
-- SESSION_SECRET. Rotating SESSION_SECRET makes existing rows undecryptable —
-- re-run the seed route after rotating.
--
-- Only create this table if you actually use those two routes.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS secret_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  encrypted_value TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS on with NO policies at all: PostgREST denies every anon and authenticated
-- request, and only the service-role key (which bypasses RLS) can read or write.
-- Do NOT add an anon policy here — these rows are encrypted credentials.
ALTER TABLE secret_keys ENABLE ROW LEVEL SECURITY;

-- Keep updated_at meaningful; the agent reports on staleness.
CREATE OR REPLACE FUNCTION set_secret_keys_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS secret_keys_set_updated_at ON secret_keys;
CREATE TRIGGER secret_keys_set_updated_at
  BEFORE UPDATE ON secret_keys
  FOR EACH ROW EXECUTE FUNCTION set_secret_keys_updated_at();
