-- Supabase schema for the Micro-SaaS Signal Engine.
--
-- This is the one table the app actually uses: "Push to Supabase" / background
-- sync (see addToSupabaseAction / syncToSupabaseAction in app/actions.ts) writes
-- saved ideas here using the public anon key.
--
-- Run this once in the Supabase SQL editor for your project.

CREATE TABLE IF NOT EXISTS saved_ideas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  tagline TEXT,
  problem TEXT,
  solution TEXT,
  target_audience TEXT,
  pain_solved TEXT,
  build_complexity TEXT,
  mrr_target TEXT,
  build_cost TEXT,
  launch_kit JSONB,
  user_email TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Row Level Security. The app inserts with the public anon key, so anon INSERT
-- is allowed — but do NOT grant anon SELECT, or every visitor could read all
-- users' saved ideas and email addresses. Read the table from the Supabase
-- dashboard or with the service-role key instead.
ALTER TABLE saved_ideas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon insert" ON saved_ideas;
CREATE POLICY "Allow anon insert" ON saved_ideas
  FOR INSERT TO anon
  WITH CHECK (true);

-- If you see "schema cache" errors after creating the table, reload the cache:
--   NOTIFY pgrst, 'reload schema';

-- ---------------------------------------------------------------------------
-- secret_keys — backs POST /api/secrets/seed and the hourly GET /api/cron/agent
-- audit. Values are AES-256-GCM ciphertext ("enc:v1:<iv>:<tag>:<ciphertext>")
-- produced by encryptSecret() in app/security.ts under SESSION_SECRET.
--
-- Both routes use the SERVICE-ROLE key, which bypasses RLS. RLS is enabled with
-- NO policies so the public anon key can never read or write this table.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS secret_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  encrypted_value TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE secret_keys ENABLE ROW LEVEL SECURITY;
-- Deliberately no policies: anon and authenticated get nothing.
DROP POLICY IF EXISTS "Allow anon insert" ON secret_keys;
DROP POLICY IF EXISTS "Allow anon select" ON secret_keys;
