-- Supabase schema for the Micro-SaaS Signal Engine.
--
-- This is the one table the app actually uses: "Push to Supabase" / background
-- sync (see addToSupabaseAction / syncToSupabaseAction in app/actions.ts) writes
-- saved ideas here using the public anon key.
--
-- Run this once in the Supabase SQL editor for your project.

CREATE TABLE IF NOT EXISTS saved_ideas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  tagline TEXT,
  problem TEXT,
  solution TEXT,
  target_audience TEXT,
  pain_solved TEXT,
  build_complexity TEXT,
  mrr_target TEXT,
  build_cost TEXT,
  launch_kit JSONB,
  user_email TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Row Level Security. The app inserts with the public anon key, so anon INSERT
-- is allowed — but do NOT grant anon SELECT, or every visitor could read all
-- users' saved ideas and email addresses. Read the table from the Supabase
-- dashboard or with the service-role key instead.
ALTER TABLE saved_ideas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon insert" ON saved_ideas;
CREATE POLICY "Allow anon insert" ON saved_ideas
  FOR INSERT TO anon
  WITH CHECK (true);

-- If you see "schema cache" errors after creating the table, reload the cache:
--   NOTIFY pgrst, 'reload schema';

-- ---------------------------------------------------------------------------
-- secret_keys — deployment credentials written by POST /api/secrets/seed
-- (operator-only) and audited by GET /api/cron/agent (CRON_SECRET-only).
-- Values are AES-256-GCM envelopes produced by encryptSecret() in
-- app/security.ts: "enc:v1:<iv>:<tag>:<ciphertext>".
--
-- RLS is ON with NO policies, so anon and authenticated roles can read nothing.
-- Both routes reach it through the service-role key, which bypasses RLS.
-- Never add a policy here.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS secret_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  encrypted_value TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE secret_keys ENABLE ROW LEVEL SECURITY;
